name: weatherapp
description: A project to demonstrate the weather data using openweathermap api

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.2+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  app_settings: ^4.1.1
  cached_network_image: ^3.1.0+1
  fl_chart: ^0.40.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_dotenv: ^5.0.2
  geocoding: ^2.0.1
  geolocator: ^9.0.2
  google_fonts: ^3.0.1
  http: ^0.13.4
  intl: ^0.17.0
  shared_preferences: ^2.0.8
  shimmer: ^2.0.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.2.10+1
  flutter_lints: ^2.0.1

flutter_icons:
  android: true
  ios: false 
  image_path: 'assets/logo.png'

flutter_native_splash:
  color: "#FFF8E1"
  color_dark: "#263238"
  image: 'assets/logo.png'
  android: true
  ios: false 
  web: false 
  fullscreen: true 

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/icon/
    - assets/api/
    - .env
