name: weatherapp
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.3
  flutter_dotenv: ^5.0.2
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^0.23.0+1
  geolocator: ^7.7.1
  http: ^0.13.4
  shared_preferences: ^2.0.8
  shimmer: ^2.0.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.3.1
  flutter_lints: ^1.0.0

flutter_icons:
  android: true
  ios: false 
  image_path: 'assets/logo.png'

flutter_native_splash:
  color: "#FFF8E1"
  color_dark: "#263238"
  image: 'assets/logo.png'
  android: true
  ios: false 
  web: false 
  fullscreen: true 

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/requests/
    - .env
